title: Introduction to Statistics with R
description: Minimal is a theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-minimal
email: nathaniel.phillips@unibas.ch
include: ['assignments', 'presentations']
