---
title: "Introduction to Statistics with R"
output:
  rmdformats::html_clean:
    highlight: kate
---


```{r knitr_init, echo=FALSE, cache=FALSE, message = FALSE, warning = FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

## Main Information

Semester: Basel, Fall, 2017/2018

Location: Missionsstrasse 64a, Computerraum 00.010

Course meeting times: 

- Session 1: Wednesdays, 14:15 - 15:45
- Session 2: Wednesdays, 16:15 - 17:45 

Syllabus (you're looking at it): [https://ndphillips.github.io/IntroductionR_Course/](https://ndphillips.github.io/IntroductionR_Course/)

Instructor: Nathaniel Phillips, nathaniel.phillips@unibas.ch


## Course Session Doodle

- If you would like to switch course sessions, please go to the following Doodle linke: [https://doodle.com/poll/g26anuhxqw4rr6mv](https://doodle.com/poll/g26anuhxqw4rr6mv). Enter your name and email address, and indicate which course you are in and if you're available to switch sessions.

- If you match with someone else, contact them and ask if they would like to switch with you. If you both agree, email me, and delete your information from the Doodle.

- On 2 October, we will finalize the the session assignments. Those in session II will need to de-register from session 1 (23496-01) and register for session 2 (23496-02)


# Schedule

Your homework for each class period is to actively read the readings for that week. The videos are optional.  All of the work you turn in will be done in class as WPAs (Weekly Programming Assignments).

*If you have trouble opening a link, try right--clicking and opening in an new browser tab.*

Week - Date |  Topic | Reading (at home) | Assignment (in class)
------ | ----------- | --------- | --------- 
1 - 20 Sep  | Introduction | [Day 0 Presentation](https://ndphillips.github.io/IntroductionR_Course/presentations/Day_0_pres.html)    | [WPA #0](https://ndphillips.github.io/IntroductionR_Course/assignments/wpa/wpa_0.html)
2 - 27 Sep | R basics, scalers and vectors | YaRrr Ch: [1](https://bookdown.org/ndphillips/YaRrr/), [2](https://bookdown.org/ndphillips/YaRrr/started.html), [3](https://bookdown.org/ndphillips/YaRrr/jumpin.html), [4](https://bookdown.org/ndphillips/YaRrr/basics.html), [5](https://bookdown.org/ndphillips/YaRrr/scalersvectors.html), [6](https://bookdown.org/ndphillips/YaRrr/vectorfunctions.html) <br> Videos: [A](https://www.youtube.com/watch?v=Vkv7-nw3wwU&list=PL9tt3I41HFS9gmeZFEuNrnu_7V_NFngfJ&index=1), [B](https://www.youtube.com/watch?v=4Dr0o3g8h3Y&list=PL9tt3I41HFS9gmeZFEuNrnu_7V_NFngfJ&index=2), [C](https://www.youtube.com/watch?v=yNVDA0Noejk&list=PL9tt3I41HFS9gmeZFEuNrnu_7V_NFngfJ&index=3) | [WPA #1](https://ndphillips.github.io/IntroductionR_Course/assignments/wpa/wpa_1.html)
3 - 4 Oct | Indexing Vectors | YaRrr Ch: [7](https://bookdown.org/ndphillips/YaRrr/vectorindexing.html) <br> Videos: [D](https://goo.gl/IsrBWO)| 
4 - 11 Oct | Matrices and Dataframes, Managing data | YaRrr Ch: [8](https://bookdown.org/ndphillips/YaRrr/matricesdataframes.html) <br> Videos: [E](https://goo.gl/w86DM6), [F](https://goo.gl/yEiJ1R)|  | 
5 - 18 Oct| Dataframe manipulation | YaRrr Ch: [9](https://bookdown.org/ndphillips/YaRrr/importingdata.html), [10](https://bookdown.org/ndphillips/YaRrr/advanceddataframe.html) <br> Videos: [G](https://goo.gl/UY2AE1) | 
6 - 25 Oct | Plotting | YaRrr Ch: [11](https://bookdown.org/ndphillips/YaRrr/plotting1.html), [12](https://bookdown.org/ndphillips/YaRrr/plotting2.html) <br> [IDRE ggplot2 intro](http://stats.idre.ucla.edu/r/seminars/ggplot2_intro/)| 
7 - 1 Nov | 1 and 2 sample Hypothesis tests |YaRrr Ch: [13](https://bookdown.org/ndphillips/YaRrr/htests.html)| 
8 - 8 Nov | ANOVA with `aov()` and `anova()`|YaRrr Ch: [14](https://bookdown.org/ndphillips/YaRrr/anova.html)|
9 - 15 Nov | Linear regression with `lm()`, `glm()` | YaRrr Ch: [15](https://bookdown.org/ndphillips/YaRrr/regression.html) | 
10 - 22 Nov | Writing Functions and Loops | YaRrr Ch: [16](https://bookdown.org/ndphillips/YaRrr/functions.html), [17](https://bookdown.org/ndphillips/YaRrr/loops.html) | 
11 - 29 Nov | R Markdown and papaja | [Markdown Video](https://www.youtube.com/watch?v=7qTvOZfK6Cw)<br>[Markdown Guide](http://www.rpubs.com/YaRrr/markdownbasics)<br>[RStudio Lessons](http://rmarkdown.rstudio.com/lesson-1.html)<br>[papaja Guide](http://www.rpubs.com/YaRrr/papaja_guide) | -
12 - 6 Dec | Final project work | - | - 
13 - 13 Dec | Final project work | - | - 
14 - 20 Dec | Final project work | -| - 
End - 9 June | Final Project Due!!! | -| - 



# R Installation

You need to install two pieces of software for this course: R, and RStudio.

- Install R version 3.4.0 "You Stupid Darkness" (or higher) here: [https://cloud.r-project.org/](https://cloud.r-project.org/)
- Install RStudio for Desktop (the free version) here: [https://www.rstudio.com/products/rstudio/download/#download](https://www.rstudio.com/products/rstudio/download/#download)

## Important Links

Link  | Description 
------ | ----------------- 
[WPA Submission Page](https://goo.gl/forms/dTVlSdtHtqiNuHSw1) | After you have emailed your WPA to me, submit your assignments here
[R Reference Card](https://cran.r-project.org/doc/contrib/Short-refcard.pdf) | A handy R cheat sheet. I recommend you print this out and have it handy.
[RStudio Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/) | R Studio provides many very helpful R cheat sheets here.


## Helpful sites

Link  | Description 
------ | ----------------- 
[http://r-bloggers.com](http://r-bloggers.com)| The #1 place to hear the latest and greatest R news. Tons of great new R content every day. I encourage you to sign up for their email list!
[http://rseek.org/](http://rseek.org/) | Use it like Google -- it only returns R related topics.



# 5 Great question to ask when you get stuck

The best advice I can give you to help you learn R is to ask questions...constantly. I learned almost everything I know about R from asking other people for help. If you find that you are stuck on a problem, here are some 5 great questions that I love to hear from students:

| Level| Problem | Question|
|----|:---------------------------------|:--------------------------------:|
| 1 |     You don't understand the problem and you have absolutely no idea how to get started.|   **Can you please help explain what the problem is and what I am supposed to do??**     |
|     2|    You understand the problem but you're not sure what a solution would look like. | **Can you please help me get started?**     |
|     3|    You understand the problem and you (think you) know a solution, but your code is not working the way you want it to. | **Can you please help me figure out what's wrong with my code?**     |
|     4|    You understand the problem, and you have a solution that works, but you don't know *why* and *how* it works.|**Can you please explain how and why this code works?**     |
|     5|    You understand the problem, you have a solution, and you know why it works, but you don't know if it is the best way to solve the problem.|  **Can you please help me figure out a better way to solve this problem?**     |



# Course Description

R is one of the most popular statistical languages for both academic researchers and data analysts working in industry. The reason why is simple - R is free, easy to use and incredibly powerful. With R you can generate and manipulate data, conduct analyses, create plots and even write documents. The goal of this course is to introduce you to R so you can apply it to your current and future research. In this course, you will learn how to use R to conduct all steps of your data analysis, from loading data to performing analyses, to producing reports.

This course is for *anyone who wants to learn R*. I don't care if you're 10 or 100 or what your background is in programming, math, or pirate history. If you want to learn R and know how to use a computer, this course is for you. That said, the course is designed around the needs of a psychology student in a Bachelor's, Masters, or PhD program who has taken at least an introductory course in statistics.

This is not a traditional course -- this is a **'flipped'** course. This means that you will be learning the basic material on your own time outside of class, by actively reading and watching videos, and then 'learn-by-doing' in class. For more information about the 'flipping' concept, check out [https://en.wikipedia.org/wiki/Flipped_classroom](https://en.wikipedia.org/wiki/Flipped_classroom).

## Materials

To learn the basic material, you will read chapters from the e-book *YaRrr! The Pirate's Guide to R*. Links to chapters to the book will be posted on the top of this page as the course progresses.

If you are interested in additional, non-piratey materials, there are numerous books and websites that can help you discover new ways of utilizing R. Here are some books I recommend

1. [Data Science with R (online)](http://r4ds.had.co.nz/) by Grolemund and Wickham. This is the best book for getting started with R using the 'tidyverse' packages. Highly recommended.
2. [Data Visualisation for Social Sciences (online)](http://socviz.co/index.html#preface) by Healy.
3. [The R Booky](http://goo.gl/sYB5rs) by Crawly.
4. [Discovering Statistics Using R](http://goo.gl/WNKxjb) by Field and Miles


## Weekly Programming Assignments (WPAs)

During each class you will work on a series of programming tasks called a **Weekly Programming Assignment (WPA)** together with one or two of your classmates. The questions on WPAs will start easy to help remind you of the reading, but end hard in order to push your knowledge of the material. At the end of class, you will email your work on the WPA to me to receive credit.

The WPAs are designed to be challening. For taht reason, I do **not** expect you to finish the entire WPA by the end of class. Work hard, ask questions, and complete as many of the problems as you can. The only way to fail your assignment is to not turn it in. You are **not** expected to continue working on WPAs outside of class. However, each WPA will have a checkpoint to help you know whether you are falling behind or not. If you reach the checkpoint by the end of class, then you are doing just fine. If you do not reach the checkpoint, I strongly encourage you to continue working on the assignment outside of class so that you do not fall behind.

I encourage you to work with a partner (or two) on WPAs. However, it is very important that each student's work is his/her own. Do not turn in any assignments that you did not contribute to or do not fully understand.

While I will keep track of how often you submit your WPAs, I will *not* grade them. I will only give you individual feedback if your work looks especially poor, or especially good. Complete answers to WPAs will be posted shortly after each class. It is your responsibility to look over the answers and compare them to your work. Of course, if you have specific questions about the assignment, please email me or come to my office and I will be very happy to help you.

## Final Project

At the end of the course you will complete a final analysis project. In this project, you will produce a report containing several key analyses from a dataset of your choosing. If you have a specific dataset you would like to analyze (such as from your thesis), you are welcome to use it. If not, I will assign one to you. I will give you more details about the project later in the course.

## Grading

This is a pass / fail course. Passing the course is not difficult. If you work hard, ask lots of questions, turn in your WPAs and complete the final analysis project, you'll pass the class. If you never ask questions, habitually fail to turn in your WPAs and turn in a poor quality final project, you may fail the course.

## Tips

Learning R will be challenging, but it will also be fun (I promise!). In order to learn the most, and have the most fun, I recommend the following

**Work together and be noisy in class!**

The best way to learn programming is with someone else by your side. For that reason, it should be noisy in class! A quiet class is typically a bored class that isn't learning anything. A noisy class is a class that's struggling, asking questions, and actually learning. If I find that the class is not noisy enough, I reserve the right to play Justin Bieber until the class gets noisy again. This is not an empty threat. 

**Use Google...the right way**

If you have a programming problem that you can't figure out the answer to, don't be afraid to Google it. I Google programming questions all the time. However, if you don't understand the answer you find, make sure to ask for help before you include it in your assignment. If you just copy and paste code that you don't understand, you won't learn anything.

